# Generated by Django 4.2.9 on 2025-07-27 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kategoriyalar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nomi", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Loyihalar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Nomi", models.CharField(max_length=100)),
                ("Tavsifi", models.TextField()),
                ("Active", models.BooleanField(default=True)),
                ("Rasm_1", models.ImageField(upload_to="rasmlar/")),
                (
                    "Rasm_2",
                    models.ImageField(blank=True, null=True, upload_to="rasmlar/"),
                ),
                (
                    "Rasm_3",
                    models.ImageField(blank=True, null=True, upload_to="rasmlar/"),
                ),
                (
                    "Rasm_4",
                    models.ImageField(blank=True, null=True, upload_to="rasmlar/"),
                ),
                (
                    "Rasm_5",
                    models.ImageField(blank=True, null=True, upload_to="rasmlar/"),
                ),
                (
                    "Rasm_6",
                    models.ImageField(blank=True, null=True, upload_to="rasmlar/"),
                ),
                ("CreatedAt", models.DateTimeField(auto_now_add=True)),
                ("UpdatedAt", models.DateTimeField(auto_now=True)),
                (
                    "Kategoriyasi",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.kategoriyalar",
                    ),
                ),
            ],
            options={
                "unique_together": {("Nomi", "Kategoriyasi")},
            },
        ),
    ]
