# Generated by Django 4.2.9 on 2025-07-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="kategoriyalar",
            name="rasmni",
            field=models.ImageField(default=1, upload_to="kategoriyalar/"),
            preserve_default=False,
        ),
    ]
