# Generated by Django 4.2.9 on 2025-07-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_kategoriyalar_rasmni"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kategoriyalar",
            name="rasmni",
            field=models.ImageField(upload_to="media/kategoriyalar/"),
        ),
        migrations.AlterField(
            model_name="loyihalar",
            name="Rasm_1",
            field=models.ImageField(upload_to="media/rasmlar/"),
        ),
        migrations.AlterField(
            model_name="loyihalar",
            name="Rasm_2",
            field=models.ImageField(blank=True, null=True, upload_to="media/rasmlar/"),
        ),
        migrations.AlterField(
            model_name="loyihalar",
            name="Rasm_3",
            field=models.ImageField(blank=True, null=True, upload_to="media/rasmlar/"),
        ),
        migrations.AlterField(
            model_name="loyihalar",
            name="Rasm_4",
            field=models.ImageField(blank=True, null=True, upload_to="media/rasmlar/"),
        ),
        migrations.AlterField(
            model_name="loyihalar",
            name="Rasm_5",
            field=models.ImageField(blank=True, null=True, upload_to="media/rasmlar/"),
        ),
        migrations.AlterField(
            model_name="loyihalar",
            name="Rasm_6",
            field=models.ImageField(blank=True, null=True, upload_to="media/rasmlar/"),
        ),
    ]
