# Generated by Django 4.2.9 on 2025-07-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_kategoriyalar_rasmni_alter_loyihalar_rasm_1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="telegram_user",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=50, unique=True)),
                ("username", models.CharField(blank=True, max_length=50, null=True)),
                ("first_name", models.CharField(blank=True, max_length=50, null=True)),
                ("telefon", models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
